# Generated by Django 4.2.23 on 2025-08-07 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, verbose_name='Identificador')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Método')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('supports_installments', models.BooleanField(default=False, verbose_name='Suporta Parcelamento')),
                ('max_installments', models.PositiveSmallIntegerField(default=1, verbose_name='Número Máximo de Parcelas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Despesa'), ('cheque', 'Cheque')], max_length=10, verbose_name='Tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('installments', models.PositiveSmallIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('installment_number', models.PositiveSmallIntegerField(default=1, verbose_name='Parcela Atual')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='Conta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Categoria')),
                ('parent_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_expenses', to='core.expense', verbose_name='Despesa Original')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentmethod', verbose_name='Método de Pagamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Despesa'), ('cheque', 'Cheque')], max_length=10, verbose_name='Tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('number', models.CharField(max_length=50, verbose_name='Número')),
                ('issue_date', models.DateField(verbose_name='Emissão')),
                ('compensation_date', models.DateField(verbose_name='Compensação')),
                ('recipient', models.CharField(max_length=200, verbose_name='Beneficiário')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('cashed', 'Compensado'), ('canceled', 'Cancelado')], default='pending', max_length=10, verbose_name='Status')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='Conta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
