# Generated by Django 5.2 on 2025-04-24 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Método')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50, verbose_name='Identificador')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Despesa'), ('cheque', 'Cheque')], max_length=10, verbose_name='Tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('number', models.CharField(max_length=50, verbose_name='Número')),
                ('issue_date', models.DateField(verbose_name='Emissão')),
                ('compensation_date', models.DateField(verbose_name='Compensação')),
                ('recipient', models.CharField(max_length=200, verbose_name='Beneficiário')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='Conta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('expense', 'Despesa'), ('cheque', 'Cheque')], max_length=10, verbose_name='Tipo')),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor')),
                ('date', models.DateField(verbose_name='Data')),
                ('description', models.CharField(max_length=200, verbose_name='Descrição')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.account', verbose_name='Conta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.category', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentmethod', verbose_name='Método de Pagamento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
