# Generated by Django 5.2 on 2025-05-01 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
