# Generated by Django 4.2.23 on 2025-08-14 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AddField(
            model_name='category',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Categorias públicas podem ser usadas por todos os usuários', verbose_name='Categoria Pública'),
        ),
    ]
