# Generated by Django 5.2 on 2025-05-01 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_expense_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='installment_number',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Parcela Atual'),
        ),
        migrations.AddField(
            model_name='expense',
            name='installments',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.AddField(
            model_name='expense',
            name='parent_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_expenses', to='core.expense', verbose_name='Despesa Original'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='max_installments',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Número Máximo de Parcelas'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='supports_installments',
            field=models.BooleanField(default=False, verbose_name='Suporta Parcelamento'),
        ),
    ]
