# Generated by Django 4.2.23 on 2025-10-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_account_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cheque',
            options={'ordering': ['-compensation_date', '-id'], 'verbose_name': 'Cheque', 'verbose_name_plural': 'Cheques'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'Despesa', 'verbose_name_plural': 'Despesas'},
        ),
    ]
