# Generated by Django 5.2 on 2025-05-01 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_expense_installment_number_expense_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('cashed', 'Compensado'), ('canceled', 'Cancelado')], default='pending', max_length=10, verbose_name='Status'),
        ),
    ]
